services:
  adminer:
    image: adminer:latest
    container_name: minegnk-adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DESIGN: dracula
    extra_hosts:
      - 'host.docker.internal:host-gateway'
